spring.application.name=MonitoreoFlotas

spring.datasource.url = jdbc:postgresql://localhost:5433/simonflotas
spring.datasource.username = postgres
spring.datasource.password = 12345
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto= create-drop

jwt.secret = 1c3afa17e913208dd686e9d09f9569cc1d312d92d71cd0a562bfc05738eddf35
jwt.expiration = 3600
